
name: tgbot-test

x-env-file: &env-file
  env_file:
    - path: ./defaults.env
      required: true
    - path: ./test.env
      required: true

services:
  redis:
    <<: *env-file
    ports:
      - "${HOST_REDIS_PORT}:6379"
  postgres:
    <<: *env-file
    ports:
      - "${HOST_POSTGRES_PORT}:5432"
  mongo:
    <<: *env-file
    ports:
      - "${HOST_MONGO_PORT}:27017"
  tgbot:
    <<: *env-file

# docker-compose --env-file test.env -f compose.yaml -f compose.test.yaml
