
#version: '3.8'

x-env-file: &env-file
  env_file:
    - path: ./defaults.env
      required: true
    - path: ./secrets.env
      required: false

services:
  postgres:
    # postgres:14.16-alpine3.20 for example
    image: @postgres_imageid@
    restart: always
    ports:
      - "5432:5432"
    <<: *env-file
    # POSTGRES_USER
    # POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    # redis:alpine3.21 for example
    image: @redis_imageid@
    restart: always
    ports:
      - "6379:6379"
    <<: *env-file
    # REDIS_PASSWORD

  mongodb:
    # mongo:noble for example
    image: @mongo_imageid@
    restart: always
    ports:
      - "27017:27017"
    <<: *env-file
    # MONGO_INITDB_ROOT_USERNAME
    # MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb_data:/data/db

  tgbot:
    image: tgbot:latest
    restart: always
    <<: *env-file
    # BOT_TOKEN

volumes:
  postgres_data:
  mongodb_data:

#volumes:
#  db:

#networks:
    # all services share the same network by default
    # unless explicitly specified
    #
    #default: {}


# .env file variables required
# POSTGRES_USER
# POSTGRES_PASSWORD
# MONGO_INITDB_ROOT_USERNAME
# MONGO_INITDB_ROOT_PASSWORD
# REDIS_PASSWORD
# BOT_TOKEN
